name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5 
        with:
          go-version: '1.23'

      - run: go build -o server .

      - run: docker build -t api-go .


      - run: |
          docker compose up -d
          sleep 15
          curl -f http://localhost:3000/users || echo "api nao respondeu, ver logs"
          docker compose down
